export const mockUsers = [
    { id: 1, name: 'Mohit', age: 21, password: 'password1' },
    { id: 2, name: 'Vilek', age: 24, password: 'password2' },
    { id: 3, name: 'Aarav', age: 28, password: 'password3' },
    { id: 4, name: 'Sanya', age: 22, password: 'password4' },
    { id: 5, name: 'Rajesh', age: 35, password: 'password5' },
    { id: 6, name: 'Niharika', age: 27, password: 'password6' },
    { id: 7, name: 'Vikram', age: 30, password: 'password7' },
    { id: 8, name: 'Priya', age: 26, password: 'password8' },
    { id: 9, name: 'Ankit', age: 23, password: 'password9' },
    { id: 10, name: 'Meera', age: 29, password: 'password10' },
    { id: 11, name: 'Suraj', age: 33, password: 'password11' },
    { id: 12, name: 'Ishita', age: 25, password: 'password12' },
    { id: 13, name: 'Karan', age: 32, password: 'password13' },
    { id: 14, name: 'Tara', age: 20, password: 'password14' },
    { id: 15, name: 'Rahul', age: 31, password: 'password15' },
    { id: 16, name: 'Sneha', age: 24, password: 'password16' },
    { id: 17, name: 'Amit', age: 29, password: 'password17' },
    { id: 18, name: 'Divya', age: 26, password: 'password18' },
    { id: 19, name: 'Rohan', age: 28, password: 'password19' },
    { id: 20, name: 'Ayesha', age: 21, password: 'password20' }
];
